apiVersion: v1
kind: Secret
metadata:
  name: veterinaria-secret
  namespace: veterinaria
type: Opaque
stringData:
  POSTGRES_PASSWORD: tupassword123
  SPRING_DATASOURCE_PASSWORD: tupassword123
  JWT_SECRET: unaClaveSecretaMuyLargaYSegura123456789
